### ISSUE TITLE
Reading a stream to the end?

### ISSUE THREAD

**Issue by hypesystem** [bmavity/ges-client#35]
Currently, `readStreamEventsForward` (and `Backward`) require a `count` field to be in the options (see code [here](https://github.com/bmavity/ges-client/blob/59365ba40cd6ede623ec05d39b601151e26985e9/tcp/connection.js#L215-L220)).

Is there a reason for requiring this? This doesn't allow for reading a stream *to the end*, which I think is a fairly common use case.

**Comment by gregoryyoung** [comment]
Sure it does if its less than that amount you will get less.

Reading to the end doesn't make much sense when you have 50m events.
Normally you would want to page through them

On Mon, Apr 27, 2015 at 1:54 PM, Niels Abildgaard <notifications@github.com>
wrote:

> Currently, readStreamEventsForward (and Backward) require a count field
> to be in the options (see code here
> <https://github.com/bmavity/ges-client/blob/59365ba40cd6ede623ec05d39b601151e26985e9/tcp/connection.js#L215-L220>
> ).
>
> Is there a reason for requiring this? This doesn't allow for reading a
> stream *to the end*, which I think is a fairly common use case.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bmavity/ges-client/issues/35>.
>



-- 
Studying for the Turing test

**Comment by gregoryyoung** [comment]
Said differently... Avoid unbounded operations.

On Mon, Apr 27, 2015 at 1:55 PM, Greg Young <gregoryyoung1@gmail.com> wrote:

> Sure it does if its less than that amount you will get less.
>
> Reading to the end doesn't make much sense when you have 50m events.
> Normally you would want to page through them
>
> On Mon, Apr 27, 2015 at 1:54 PM, Niels Abildgaard <
> notifications@github.com> wrote:
>
>> Currently, readStreamEventsForward (and Backward) require a count field
>> to be in the options (see code here
>> <https://github.com/bmavity/ges-client/blob/59365ba40cd6ede623ec05d39b601151e26985e9/tcp/connection.js#L215-L220>
>> ).
>>
>> Is there a reason for requiring this? This doesn't allow for reading a
>> stream *to the end*, which I think is a fairly common use case.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/bmavity/ges-client/issues/35>.
>>
>
>
>
> --
> Studying for the Turing test
>



-- 
Studying for the Turing test

**Comment by hypesystem** [comment]
I get the general sentiment. I could definitely work around it (and am about to in the case where I need it).

If the only way to get the desired result is to read *all events* of a type, I don't necessarily see an advantage to paging. I get the general sentiment that unbounded operations are bad (because runtime, etc), but in my case I need all the events in a stream --- why is paging better than just reading the entire stream?

**Comment by gregoryyoung** [comment]
What about other requests happening over the connection as example?

1 get -> 700 bytes
2 get -> 800 bytes
3 get -> 3.7GB
4 get -> 300 bytes
5 write -> 900 bytes

What happens to req 4/5 there

We will leave out the derpyness of serializing out this response using
something like protobufs.



Beyond a paged view is needed anyways ... why do all the work twice.
Implementing "read to end" is < 10 minutes worth of work over a paged model
and is actually included (catch up subscription can do this though its a
bit of overkill I would just write the loop)


On Mon, Apr 27, 2015 at 2:09 PM, Niels Abildgaard <notifications@github.com>
wrote:

> I get the general sentiment. I could definitely work around it (and am
> about to in the case where I need it).
>
> If the only way to get the desired result is to read *all events* of a
> type, I don't necessarily see an advantage to paging. I get the general
> sentiment that unbounded operations are bad (because runtime, etc), but in
> my case I need all the events in a stream --- why is paging better than
> just reading the entire stream?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bmavity/ges-client/issues/35#issuecomment-96611112>.
>



-- 
Studying for the Turing test

**Comment by hypesystem** [comment]
Fair enough -- good explanation. Thanks :)
