### ISSUE TITLE
Is this still being used/maintained?

### ISSUE THREAD

**Issue by ruprict** [bmavity/ges-client#36]
Sorry for making this an issue, but we just found this and it's pretty nice. Almost exactly what we're looking for.  

I tried the Gitter room, but it was empty and the last message was long ago and far away...

Anyway...are the maintainers still using this?

**Comment by bmavity** [comment]
Hi. :) While this project has tests, I am not currently using it in production due to scheduling issues with a client of mine. However, I will be adding it to a production site within the next month so will be updating / fixing bugs as I find them.

**Comment by ruprict** [comment]
Yay! 

FYI, I've quickly prototyped a node service to subscribe and keep track of where it is on a stream. We start work in about 2 weeks, so if we find anything, we'll create issues.

**Comment by bmavity** [comment]
Sound good. It will be great to start getting some feedback.
