### ISSUE TITLE
Where is version 0.9.1?

### ISSUE THREAD

**Issue by hypesystem** [bmavity/ges-client#37]
In this repository the version in package.json is currently 0.9.0. The [most recently published version](https://www.npmjs.com/package/ges-client) is 0.9.1.

What has changed between the versions? Why isn't the most recent version in this repository?

**Comment by bmavity** [comment]
Ugh, apologies. I must have forgotten to tag it. My guess is that 0.9.1 matches the current master branch code.

There will be a new release in the next couple of weeks. It will be tagged and have a list of changes.

**Comment by hypesystem** [comment]
awesome :)

**Comment by bmavity** [comment]
There were a couple of commits on my machine that were part of the publish. I pushed them and tagged. I am getting v0.9.2 organized now.
