### ISSUE TITLE
data type/schema issue

### ISSUE THREAD

**Issue by reharik** [bmavity/ges-client#54]
Hey, I'm getting this error  
throw TypeError("Illegal str: Length not a multiple of 4");
so I looked at a bunch of stuff then I looked at the data schema.  I'm not sure if i have the right format for my data.  The schema ( in ges_client.proto ) is 
message NewEvent {
   required bytes event_id = 1;
   required string event_type = 2;
   required int32 data_content_type = 3;
   required int32 metadata_content_type = 4;
   required bytes data = 5;
   optional bytes metadata = 6;
}
the schema of my events looks like this
EventId : uuid.v4(),
Type    : eventName,
IsJson  : true,
Data    : data,
Metadata: metadata
this is what I was using in the past, and it seemed to work ok.  However, it certainly doesn't look like a direct map.
lastly here is what my test event data looks like 
EventId: uuid.v4() ,Type:'bootstrapApplication', IsJson: true, Data: { data:'bootstrap please' }, Metadata: {commandTypeName:'bootstrapApplication'}
Here's my stack trace. 
thanks
Raif

```
            throw TypeError("Illegal str: Length not a multiple of 4");
```

plugin_1        |                       ^
plugin_1        | TypeError: Illegal str: Length not a multiple of 4
plugin_1        |     at TypeError (native)
plugin_1        |     at Function.module.exports.ByteBuffer.fromBase64 (/home/opt/app/node_modules/ges-client/node_modules/protobufjs/node_modules/bytebuffer/dist/ByteBufferNB.js:2864:23)
plugin_1        |     at Function.module.exports.ByteBuffer.wrap (/home/opt/app/node_modules/ges-client/node_modules/protobufjs/node_modules/bytebuffer/dist/ByteBufferNB.js:332:39)
plugin_1        |     at [object Object].ProtoBuf.Reflect.ElementPrototype.verifyValue (/home/opt/app/node_modules/ges-client/node_modules/protobufjs/dist/ProtoBuf.js:1937:39)
plugin_1        |     at [object Object].ProtoBuf.Reflect.FieldPrototype.verifyValue (/home/opt/app/node_modules/ges-client/node_modules/protobufjs/dist/ProtoBuf.js:3536:33)
plugin_1        |     at [object Object].MessagePrototype.set (/home/opt/app/node_modules/ges-client/node_modules/protobufjs/dist/ProtoBuf.js:2542:59)
plugin_1        |     at [object Object].MessagePrototype.set (/home/opt/app/node_modules/ges-client/node_modules/protobufjs/dist/ProtoBuf.js:2533:38)
plugin_1        |     at [object Object].Message (/home/opt/app/node_modules/ges-client/node_modules/protobufjs/dist/ProtoBuf.js:2462:34)
plugin_1        |     at [object Object].ProtoBuf.Reflect.ElementPrototype.verifyValue (/home/opt/app/node_modules/ges-client/node_modules/protobufjs/dist/ProtoBuf.js:1976:28)
plugin_1        |     at [object Object].ProtoBuf.Reflect.FieldPrototype.verifyValue (/home/opt/app/node_modules/ges-client/node_modules/protobufjs/dist/ProtoBuf.js:3517:43)
plugin_1        |     at [object Object].MessagePrototype.set (/home/opt/app/node_modules/ges-client/node_modules/protobufjs/dist/ProtoBuf.js:2542:59)
plugin_1        |     at [object Object].MessagePrototype.set (/home/opt/app/node_modules/ges-client/node_modules/protobufjs/dist/ProtoBuf.js:2533:38)
plugin_1        |     at [object Object].Message (/home/opt/app/node_modules/ges-client/node_modules/protobufjs/dist/ProtoBuf.js:2462:34)
plugin_1        |     at Object.serialize (/home/opt/app/node_modules/ges-client/tcp/messageParser.js:28:9)
plugin_1        |     at Object.toRequestPayload (/home/opt/app/node_modules/ges-client/tcp/operations.js:70:26)
plugin_1        |     at OperationItem.toTcpMessage (/home/opt/app/node_modules/ges-client/tcp/operations.js:19:24)
plugin_1        |     at OperationsManager.scheduleOperation (/home/opt/app/node_modules/ges-client/tcp/operationsManager.js:35:38)
plugin_1        |     at EsConnectionLogicHandler.states.Connected.StartOperation (/home/opt/app/node_modules/ges-client/tcp/connectionLogicHandler.js:77:23)
plugin_1        |     at EsConnectionLogicHandler._processNextMessage (/home/opt/app/node_modules/ges-client/tcp/connectionLogicHandler.js:236:10)
plugin_1        |     at Immediate._onImmediate (/home/opt/app/node_modules/ges-client/tcp/connectionLogicHandler.js:212:6)
plugin_1        |     at processImmediate [as _immediateCallback](timers.js:367:17)
plugin_1        |

**Comment by bmavity** [comment]
Hi @reharik 

When you are creating the event data manually, the Data and Metadata properties need to be buffers. The fact that it worked before was a bug and not a feature. ;) You will get a similar issue if you use the client.createEventData method (see eventData.js). Set the data property with Data: new Buffer(JSON.stringify(data)).

I will close for now, let me know if there's still an issue.
