### ISSUE TITLE
Consider using protobufjs for compatibility with recent node version

### ISSUE THREAD

**Issue by nicdex** [bmavity/ges-client#58]
Explore the possibility of using protobufjs package instead of protobuf.

The protobuf package use native code which is blocking compatibility with node version higher than 0.10.x. Relying on a package that doesn't require native bindings would be better. protobufjs seems to be implementing the full protocol. Of course someone would need to dive into the specific to make sure that it supports what is needed for ges-client.

Note: the protobuf package seems to compile with node 0.12 despite the warning, but I guess it is untested.

**Comment by bmavity** [comment]
Hi @nicdex , since the last release (v0.10.0), ges-client has been using protobufjs. (see #51)

**Comment by nicdex** [comment]
That's great :+1: . Then I need to update.
